create table "public"."assistants" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."assistants" enable row level security;

create table "public"."assistants_template" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."assistants_template" enable row level security;

CREATE UNIQUE INDEX assistants_pkey ON public.assistants USING btree (id);

CREATE UNIQUE INDEX assistants_template_pkey ON public.assistants_template USING btree (id);

alter table "public"."assistants" add constraint "assistants_pkey" PRIMARY KEY using index "assistants_pkey";

alter table "public"."assistants_template" add constraint "assistants_template_pkey" PRIMARY KEY using index "assistants_template_pkey";

grant delete on table "public"."assistants" to "anon";

grant insert on table "public"."assistants" to "anon";

grant references on table "public"."assistants" to "anon";

grant select on table "public"."assistants" to "anon";

grant trigger on table "public"."assistants" to "anon";

grant truncate on table "public"."assistants" to "anon";

grant update on table "public"."assistants" to "anon";

grant delete on table "public"."assistants" to "authenticated";

grant insert on table "public"."assistants" to "authenticated";

grant references on table "public"."assistants" to "authenticated";

grant select on table "public"."assistants" to "authenticated";

grant trigger on table "public"."assistants" to "authenticated";

grant truncate on table "public"."assistants" to "authenticated";

grant update on table "public"."assistants" to "authenticated";

grant delete on table "public"."assistants" to "service_role";

grant insert on table "public"."assistants" to "service_role";

grant references on table "public"."assistants" to "service_role";

grant select on table "public"."assistants" to "service_role";

grant trigger on table "public"."assistants" to "service_role";

grant truncate on table "public"."assistants" to "service_role";

grant update on table "public"."assistants" to "service_role";

grant delete on table "public"."assistants_template" to "anon";

grant insert on table "public"."assistants_template" to "anon";

grant references on table "public"."assistants_template" to "anon";

grant select on table "public"."assistants_template" to "anon";

grant trigger on table "public"."assistants_template" to "anon";

grant truncate on table "public"."assistants_template" to "anon";

grant update on table "public"."assistants_template" to "anon";

grant delete on table "public"."assistants_template" to "authenticated";

grant insert on table "public"."assistants_template" to "authenticated";

grant references on table "public"."assistants_template" to "authenticated";

grant select on table "public"."assistants_template" to "authenticated";

grant trigger on table "public"."assistants_template" to "authenticated";

grant truncate on table "public"."assistants_template" to "authenticated";

grant update on table "public"."assistants_template" to "authenticated";

grant delete on table "public"."assistants_template" to "service_role";

grant insert on table "public"."assistants_template" to "service_role";

grant references on table "public"."assistants_template" to "service_role";

grant select on table "public"."assistants_template" to "service_role";

grant trigger on table "public"."assistants_template" to "service_role";

grant truncate on table "public"."assistants_template" to "service_role";

grant update on table "public"."assistants_template" to "service_role";


